import type Phaser from 'phaser';

import {
  KENNEY_BG_COLOR_HILLS,
  KENNEY_BG_COLOR_HILLS_PATH,
  KENNEY_BG_COLOR_DESERT,
  KENNEY_BG_COLOR_DESERT_PATH,
  KENNEY_BG_CLOUDS,
  KENNEY_BG_CLOUDS_PATH,
  KENNEY_BG_SOLID_SKY,
  KENNEY_BG_SOLID_SKY_PATH,
  HAZARD_CRATE,
  HAZARD_CRATE_PATH,
  COIN_1,
  COIN_1_PATH,
  ENEMY_BLOCK_1,
  ENEMY_BLOCK_1_PATH,
  ENEMY_BLOCK_2,
  ENEMY_BLOCK_2_PATH,
  FISH_YELLOW_REST,
  FISH_YELLOW_REST_PATH,
  FISH_YELLOW_SWIM_A,
  FISH_YELLOW_SWIM_A_PATH,
  FISH_YELLOW_SWIM_B,
  FISH_YELLOW_SWIM_B_PATH,
  TERRAIN_GRASS_BOTTOM,
  TERRAIN_GRASS_BOTTOM_PATH,
  TERRAIN_GRASS_TOP,
  TERRAIN_GRASS_TOP_PATH,
  PICKUP_TOKEN,
  PICKUP_TOKEN_PATH,
  PLAYER_HIT,
  PLAYER_HIT_PATH,
  PLAYER_IDLE,
  PLAYER_IDLE_PATH,
  PLAYER_WALK_A,
  PLAYER_WALK_A_PATH,
  PLAYER_WALK_B,
  PLAYER_WALK_B_PATH,
  UI_RECTANGLE_GRADIENT,
  UI_RECTANGLE_GRADIENT_PATH,
  UI_ROUND_FLAT,
  UI_ROUND_FLAT_PATH
} from './kenney';
import {
  MUSIC_BG_NORMAL,
  MUSIC_BG_NORMAL_PATH,
  MUSIC_BG_SLIDE,
  MUSIC_BG_SLIDE_PATH,
  MUSIC_SPLASH_LOOP,
  MUSIC_SPLASH_LOOP_PATH,
  SFX_PICKUP_COIN,
  SFX_PICKUP_COIN_PATH,
  SFX_PLAYER_DEAD,
  SFX_PLAYER_DEAD_PATH,
  SFX_PLAYER_JUMP,
  SFX_PLAYER_JUMP_PATH,
  SFX_PLAYER_SLIDE,
  SFX_PLAYER_SLIDE_PATH,
  SFX_PLAYER_STEPS,
  SFX_PLAYER_STEPS_PATH
} from './audio';
import { SPLASH_SCREEN_BG, SPLASH_SCREEN_BG_PATH } from './splash';

export const loadKenneyAssets = (scene: Phaser.Scene) => {
  scene.load.image(KENNEY_BG_SOLID_SKY, KENNEY_BG_SOLID_SKY_PATH);
  scene.load.image(KENNEY_BG_COLOR_HILLS, KENNEY_BG_COLOR_HILLS_PATH);
  scene.load.image(KENNEY_BG_COLOR_DESERT, KENNEY_BG_COLOR_DESERT_PATH);
  scene.load.image(KENNEY_BG_CLOUDS, KENNEY_BG_CLOUDS_PATH);

  scene.load.image(PLAYER_WALK_A, PLAYER_WALK_A_PATH);
  scene.load.image(PLAYER_WALK_B, PLAYER_WALK_B_PATH);
  scene.load.image(PLAYER_IDLE, PLAYER_IDLE_PATH);
  scene.load.image(PLAYER_HIT, PLAYER_HIT_PATH);
  scene.load.image(PICKUP_TOKEN, PICKUP_TOKEN_PATH);
  scene.load.image(HAZARD_CRATE, HAZARD_CRATE_PATH);
  scene.load.image(COIN_1, COIN_1_PATH);
  scene.load.image(ENEMY_BLOCK_1, ENEMY_BLOCK_1_PATH);
  scene.load.image(ENEMY_BLOCK_2, ENEMY_BLOCK_2_PATH);
  scene.load.image(FISH_YELLOW_REST, FISH_YELLOW_REST_PATH);
  scene.load.image(FISH_YELLOW_SWIM_A, FISH_YELLOW_SWIM_A_PATH);
  scene.load.image(FISH_YELLOW_SWIM_B, FISH_YELLOW_SWIM_B_PATH);
  scene.load.image(TERRAIN_GRASS_TOP, TERRAIN_GRASS_TOP_PATH);
  scene.load.image(TERRAIN_GRASS_BOTTOM, TERRAIN_GRASS_BOTTOM_PATH);
  scene.load.image(UI_RECTANGLE_GRADIENT, UI_RECTANGLE_GRADIENT_PATH);
  scene.load.image(UI_ROUND_FLAT, UI_ROUND_FLAT_PATH);
  scene.load.image(SPLASH_SCREEN_BG, SPLASH_SCREEN_BG_PATH);

  scene.load.audio(SFX_PLAYER_DEAD, SFX_PLAYER_DEAD_PATH);
  scene.load.audio(SFX_PLAYER_JUMP, SFX_PLAYER_JUMP_PATH);
  scene.load.audio(SFX_PLAYER_SLIDE, SFX_PLAYER_SLIDE_PATH);
  scene.load.audio(SFX_PLAYER_STEPS, SFX_PLAYER_STEPS_PATH);
  scene.load.audio(SFX_PICKUP_COIN, SFX_PICKUP_COIN_PATH);
  scene.load.audio(MUSIC_BG_NORMAL, MUSIC_BG_NORMAL_PATH);
  scene.load.audio(MUSIC_BG_SLIDE, MUSIC_BG_SLIDE_PATH);
  scene.load.audio(MUSIC_SPLASH_LOOP, MUSIC_SPLASH_LOOP_PATH);
};
